package com.cst2335.final_project.database;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * This class represents the object cocktail and its corresponding attributes.
 */

@Entity
public class Cocktail {

    //Autogenerated ID for database purposes.
    @PrimaryKey ()
    @ColumnInfo(name="id")
    public int id;

    @ColumnInfo(name="drinkName")
    String drinkName;

    @ColumnInfo(name="Instructions")
    String instructions;

    @ColumnInfo(name="ingredientOne")
    String ingredientOne;

    @ColumnInfo(name="ingredientTwo")
    String ingredientTwo;

    @ColumnInfo(name="ingredientThree")
    String ingredientThree;

    @ColumnInfo(name="thumnail")
    String thumbnail;

    //Default constructor for Cocktail
    public Cocktail() {

    }

    public Cocktail (int id, String imageURL, String name, String instructions,
                     String one, String two, String three){

        this.id = id;
        this.thumbnail = imageURL;
        this.drinkName = name;
        this.instructions = instructions;
        this.ingredientOne = one;
        this.ingredientTwo = two;
        this.ingredientThree = three;
    }

    //getters for class Cocktail
    public String getDrinkName() {
        return this.drinkName;
    }

    public String getInstructions() {
        return this.instructions;
    }

    public String getIngredientOne() {
        return this.ingredientOne;
    }

    public String getIngredientTwo() {
        return this.ingredientTwo;
    }

    public String getIngredientThree() {
        return this.ingredientThree;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setDrinkName(String drinkName) {
        this.drinkName = drinkName;
    }

    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    public void setIngredientOne(String ingredientOne) {
        this.ingredientOne = ingredientOne;
    }

    public void setIngredientTwo(String ingredientTwo) {
        this.ingredientTwo = ingredientTwo;
    }

    public void setIngredientThree(String ingredientThree) {
        this.ingredientThree = ingredientThree;
    }

    public String getThumbnail() {
        return thumbnail;
    }

    public void setThumbnail(String thumbnail) {
        this.thumbnail = thumbnail;
    }


}


