package com.cst2335.final_project;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * This class represents the object cocktail and its corresponding attributes.
 */

@Entity
public class Cocktail {

    //Autogenerated ID for database purposes.
    @PrimaryKey (autoGenerate = true)
    @ColumnInfo(name="id")
    public int id;

    @ColumnInfo(name="drinkName")
    String drinkName;

    @ColumnInfo(name="Instructions")
    String instructions;

    @ColumnInfo(name="ingredientOne")
    String ingredientOne;

    @ColumnInfo(name="ingredientTwo")
    String ingredientTwo;

    @ColumnInfo(name="ingredientThree")
    String getIngredientThree;

    //Default constructor for Cocktail
    public Cocktail() {

    }

    public Cocktail (int id, String name, String instructions,
                     String one, String two, String three){
        this.id = id;
        this.drinkName = name;
        this.instructions = instructions;
        this.ingredientOne = one;
        this.ingredientTwo = two;
        this.getIngredientThree = three;
    }

    //getters for class Cocktail
    public String getDrinkName() {
        return this.drinkName;
    }

    public String getInstructions() {
        return this.instructions;
    }

    public String getIngredientOne() {
        return this.ingredientOne;
    }

    public String getIngredientTwo() {
        return this.ingredientTwo;
    }

    public String getGetIngredientThree() {
        return this.getIngredientThree;
    }
}


